/**
 * Communes per wilaya, keyed by wilaya name (matching WILAYAS[].name).
 *
 * Used to suggest communes in the commune picker once a wilaya is chosen. This
 * is a starter dataset covering the most active wilayas; the CommuneCombobox
 * always allows a free-typed value, so a wilaya missing here (or a commune not
 * in the list) never blocks data entry. Extend these lists as needed.
 */
export const COMMUNES_BY_WILAYA: Record<string, string[]> = {
  Alger: [
    "Alger Centre",
    "Sidi M'Hamed",
    "El Madania",
    "Belouizdad",
    "Bab El Oued",
    "Bologhine",
    "Casbah",
    "Oued Koriche",
    "Bir Mourad Raïs",
    "El Biar",
    "Bouzareah",
    "Birkhadem",
    "El Harrach",
    "Baraki",
    "Oued Smar",
    "Bourouba",
    "Hussein Dey",
    "Kouba",
    "Bachedjerrah",
    "Dar El Beïda",
    "Bab Ezzouar",
    "Ben Aknoun",
    "Dely Ibrahim",
    "Hammamet",
    "Raïs Hamidou",
    "Djasr Kasentina",
    "El Mouradia",
    "Hydra",
    "Mohammadia",
    "Bordj El Kiffan",
    "El Magharia",
    "Beni Messous",
    "Bordj El Bahri",
    "El Marsa",
    "Aïn Taya",
    "H'raoua",
    "Rouiba",
    "Reghaïa",
    "Aïn Benian",
    "Staoueli",
    "Zeralda",
    "Mahelma",
    "Rahmania",
    "Souidania",
    "Cheraga",
    "Ouled Fayet",
    "El Achour",
    "Draria",
    "Douera",
    "Baba Hassen",
    "Khraicia",
    "Saoula",
    "Les Eucalyptus",
    "Sidi Moussa",
    "Aïn Naâdja",
    "Birtouta",
    "Ouled Chebel",
    "Tessala El Merdja",
  ],
  Oran: [
    "Oran",
    "Gdyel",
    "Bir El Djir",
    "Hassi Bounif",
    "Es Senia",
    "Arzew",
    "Bethioua",
    "Marsat El Hadjadj",
    "Aïn El Turk",
    "El Ançor",
    "Oued Tlelat",
    "Tafraoui",
    "Sidi Chami",
    "Boufatis",
    "Mers El Kébir",
    "Bousfer",
    "El Kerma",
    "El Braya",
    "Hassi Ben Okba",
    "Ben Freha",
    "Hassi Mefsoukh",
    "Sidi Ben Yebka",
    "Messerghin",
    "Boutlelis",
    "Aïn Kerma",
    "Aïn Biya",
  ],
  Constantine: [
    "Constantine",
    "Hamma Bouziane",
    "El Khroub",
    "Aïn Abid",
    "Beni Hamiden",
    "Zighoud Youcef",
    "Didouche Mourad",
    "El Haria",
    "Aïn Smara",
    "Ibn Ziad",
    "Messaoud Boudjeriou",
    "Ouled Rahmoune",
  ],
  Blida: [
    "Blida",
    "Chréa",
    "Bouarfa",
    "Ouled Yaïch",
    "Chiffa",
    "Beni Mered",
    "Boufarik",
    "Larbaâ",
    "Oued El Alleug",
    "Guerrouaou",
    "Soumaa",
    "Mouzaïa",
    "El Affroun",
    "Chebli",
    "Bougara",
    "Ouled Slama",
    "Beni Tamou",
    "Bouinan",
    "Hammam Melouane",
    "Ben Khelil",
    "Souhane",
    "Meftah",
    "Djebabra",
    "Aïn Romana",
    "Oued Djer",
  ],
  Boumerdès: [
    "Boumerdès",
    "Boudouaou",
    "Afir",
    "Bordj Menaïel",
    "Baghlia",
    "Sidi Daoud",
    "Naciria",
    "Djinet",
    "Isser",
    "Zemmouri",
    "Si Mustapha",
    "Tidjelabine",
    "Chabet el Ameur",
    "Thenia",
    "Timezrit",
    "Corso",
    "Ouled Moussa",
    "Larbatache",
    "Bouzegza Keddara",
    "Taourga",
    "Ouled Aïssa",
    "Ben Choud",
    "Dellys",
    "Ammal",
    "Beni Amrane",
    "Souk El Had",
    "Boudouaou El Bahri",
    "Ouled Hedadj",
    "Laghata",
    "Hammedi",
    "Khemis El Khechna",
    "El Kharrouba",
  ],
  "Tizi Ouzou": [
    "Tizi Ouzou",
    "Aïn El Hammam",
    "Akbil",
    "Freha",
    "Souamaâ",
    "Mekla",
    "Tizi Rached",
    "Azazga",
    "Iloula Oumalou",
    "Yakouren",
    "Larbaâ Nath Irathen",
    "Tizi N'Tleta",
    "Beni Douala",
    "Draa El Mizan",
    "Tizi Gheniff",
    "Boghni",
    "Ouadhias",
    "Azeffoun",
    "Tigzirt",
    "Makouda",
    "Draa Ben Khedda",
    "Ouaguenoun",
    "Aïn Zaouia",
    "M'Kira",
    "Tadmaït",
    "Beni Aïssi",
    "Beni Zmenzer",
    "Iferhounène",
    "Azzefoun",
    "Illoula",
    "Maâtkas",
    "Aït Aggouacha",
    "Boudjima",
    "Iflissen",
    "Mizrana",
  ],
  Sétif: [
    "Sétif",
    "Aïn El Kebira",
    "Beni Aziz",
    "Ouled Sabor",
    "Guenzet",
    "Talaifacene",
    "Bougaa",
    "Beni Ouartilane",
    "Aïn Roua",
    "Guellal",
    "Aïn Arnat",
    "Aïn Oulmene",
    "Amoucha",
    "El Eulma",
    "Djemila",
    "Beni Fouda",
    "Salah Bey",
    "Aïn Azel",
    "Bir El Arch",
    "Bousselam",
    "Hammam Guergour",
    "Aïn Legradj",
    "Bir Haddada",
  ],
  Annaba: [
    "Annaba",
    "El Bouni",
    "El Hadjar",
    "Sidi Amar",
    "Berrahal",
    "Aïn Berda",
    "Chetaïbi",
    "Seraïdi",
    "Oued El Aneb",
    "Cheurfa",
    "Treat",
    "Eulma",
  ],
  Béjaïa: [
    "Béjaïa",
    "Amizour",
    "Aokas",
    "Tichy",
    "Souk El Ténine",
    "El Kseur",
    "Sidi Aïch",
    "Akbou",
    "Seddouk",
    "Timezrit",
    "Adekar",
    "Kherrata",
    "Barbacha",
    "Tazmalt",
    "Ouzellaguen",
    "Chemini",
    "Tamokra",
    "Feraoun",
    "Boukhelifa",
    "Toudja",
  ],
  Tipaza: [
    "Tipaza",
    "Cherchell",
    "Hadjout",
    "Koléa",
    "Fouka",
    "Bou Ismaïl",
    "Aïn Tagourait",
    "Douaouda",
    "Sidi Rached",
    "Nador",
    "Bourkika",
    "Menaceur",
    "Sidi Amar",
    "Gouraya",
    "Damous",
    "Larhat",
    "Messelmoun",
    "Ahmer El Aïn",
    "Attatba",
    "Merad",
    "Hadjret Ennous",
  ],
};
