export const SPECIALTIES = [
  "Généraliste",
  "Nutritionniste",
  "Cardiologue",
  "Dermatologue",
  "Endocrinologue",
  "Gastro-entérologue",
  "Gynécologue",
  "Neurologue",
  "Ophtalmologue",
  "ORL",
  "Pédiatre",
  "Pneumologue",
  "Psychiatre",
  "Radiologue",
  "Rhumatologue",
  "Urologue",
  "Chirurgien",
  "Interniste",
  "Oncologue",
  "Néphrologue",
  "Hématologue",
] as const;
